version: '3'

services:
  server:
    build:
      context: ./nodejs
    container_name: server
    entrypoint: dockerize -wait tcp://database:3306 -timeout 20s npm run dev
    networks:
      - nginx_nodejs
    volumes:
      - ./nodejs:/usr/app/src
    depends_on:
      - database
  
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodejs
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - nginx_nodejs
    
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://server:3000 -timeout 40s /docker-entrypoint.sh nginx -g 'daemon off;'
    ports:
      - 8080:80
    networks:
      - nginx_nodejs
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/server.conf
    depends_on:
      - server

volumes:
  database_data:

networks:
  nginx_nodejs:
    driver: bridge